// Test generated by RoostGPT for test aman12Feb using AI Type Open AI and AI Model gpt-4


import express from "express";
import path from "path";
import mongoose from "mongoose";
import cookieParser from "cookie-parser";
import jwt from "jsonwebtoken";
import bcrypt from "bcrypt";
import request from 'supertest';

import app from './index';

jest.mock('jsonwebtoken');
jest.mock('bcrypt');

describe('GET /', () => {
  const mockUser = {
    name: 'John Doe'
  };

  beforeAll(() => {
    jwt.verify.mockReturnValue(mockUser);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  it('should render logout page with user name when user is authenticated', async () => {
    const res = await request(app).get('/');

    expect(res.status).toBe(200);
    expect(res.text).toContain(mockUser.name);
  });

  it('should return error when user is not authenticated', async () => {
    jwt.verify.mockImplementationOnce(() => {
      throw new Error('Invalid token');
    });

    const res = await request(app).get('/');

    expect(res.status).toBe(401);
    expect(res.text).toContain('Error: Invalid token');
  });
});
