// Test generated by RoostGPT for test aman12Feb using AI Type Open AI and AI Model gpt-4


import mongoose from "mongoose";

describe('Database Connection', () => {
    let db;
    beforeAll(async () => {
        db = await mongoose.connect("mongodb://127.0.0.1:27017", {dbName: "backend"});
    });

    test('should successfully connect to database', async () => {
        expect(db).toBeDefined();
        expect(mongoose.connection.readyState).toBe(1);
    });

    test('should fail to connect to database', async () => {
        try {
            await mongoose.connect("mongodb://127.0.0.1:27018", {dbName: "backend"});
        } catch (error) {
            expect(error).toBeDefined();
        }
    });

    afterAll(async () => {
        await mongoose.disconnect();
    });
});
