// Test generated by RoostGPT for test aman12Feb using AI Type Open AI and AI Model gpt-4


// import necessary modules
import mongoose from "mongoose";
import { MongoMemoryServer } from 'mongodb-memory-server';

// Create an in-memory MongoDB Server
let mongoServer;

beforeAll(async () => {
    mongoServer = new MongoMemoryServer();
    const mongoUri = await mongoServer.getUri();

    await mongoose.connect(mongoUri, {
        useNewUrlParser: true,
        useUnifiedTopology: true
    }, (err) => {
        if (err) console.error(err);
    });
});

afterAll(async () => {
    await mongoose.disconnect();
    await mongoServer.stop();
});

describe("Database Connection", () => {
    test("Database should be connected", async () => {
        const isConnected = mongoose.connection.readyState;
        expect(isConnected).toBe(1);
    });

    test("Database should be disconnected", async () => {
        await mongoose.disconnect();
        const isDisconnected = mongoose.connection.readyState;
        expect(isDisconnected).toBe(0);
    });
});
