// Test generated by RoostGPT for test aman12Feb using AI Type Open AI and AI Model gpt-4


const features = require('./features');

describe("generateLovePercent method", () => {

  test("should return a string", () => {
    expect(typeof features.generateLovePercent()).toBe('string');
  });

  test("should return a percentage", () => {
    expect(features.generateLovePercent()).toMatch(/\d+%$/);
  });

  test("should return a value between 0% and 100%", () => {
    const result = features.generateLovePercent();
    const value = parseInt(result);
    expect(value).toBeGreaterThanOrEqual(0);
    expect(value).toBeLessThanOrEqual(100);
  });

});
